# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='demoserver',
  serialized_pb='\n\x0finterface.proto\x12\ndemoserver\"T\n\x13\x45ntitySearchRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x02(\t\x12\r\n\x05query\x18\x02 \x02(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"#\n\x04Stat\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\"\x8d\x01\n\x0e\x44\x65tailedEntity\x12\r\n\x05title\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1e\n\x04stat\x18\x05 \x03(\x0b\x32\x10.demoserver.Stat\x12\x0e\n\x06topics\x18\x06 \x01(\t\x12\x0e\n\x06imgurl\x18\x07 \x01(\t\"$\n\x08ListItem\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\"9\n\x04List\x12\r\n\x05title\x18\x01 \x02(\t\x12\"\n\x04item\x18\x02 \x03(\x0b\x32\x14.demoserver.ListItem\"\x8e\x01\n\x14\x45ntitySearchResponse\x12\r\n\x05query\x18\x01 \x02(\t\x12\x13\n\x0btotal_count\x18\x02 \x02(\x05\x12,\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x1a.demoserver.DetailedEntity\x12$\n\nextra_list\x18\x04 \x03(\x0b\x32\x10.demoserver.List')




_ENTITYSEARCHREQUEST = _descriptor.Descriptor(
  name='EntitySearchRequest',
  full_name='demoserver.EntitySearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset', full_name='demoserver.EntitySearchRequest.dataset', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query', full_name='demoserver.EntitySearchRequest.query', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='demoserver.EntitySearchRequest.offset', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='demoserver.EntitySearchRequest.count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=115,
)


_STAT = _descriptor.Descriptor(
  name='Stat',
  full_name='demoserver.Stat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='demoserver.Stat.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='demoserver.Stat.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=152,
)


_DETAILEDENTITY = _descriptor.Descriptor(
  name='DetailedEntity',
  full_name='demoserver.DetailedEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='demoserver.DetailedEntity.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='demoserver.DetailedEntity.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='demoserver.DetailedEntity.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='demoserver.DetailedEntity.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stat', full_name='demoserver.DetailedEntity.stat', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topics', full_name='demoserver.DetailedEntity.topics', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgurl', full_name='demoserver.DetailedEntity.imgurl', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=155,
  serialized_end=296,
)


_LISTITEM = _descriptor.Descriptor(
  name='ListItem',
  full_name='demoserver.ListItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='demoserver.ListItem.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='demoserver.ListItem.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=298,
  serialized_end=334,
)


_LIST = _descriptor.Descriptor(
  name='List',
  full_name='demoserver.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='demoserver.List.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='demoserver.List.item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=336,
  serialized_end=393,
)


_ENTITYSEARCHRESPONSE = _descriptor.Descriptor(
  name='EntitySearchResponse',
  full_name='demoserver.EntitySearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='demoserver.EntitySearchResponse.query', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_count', full_name='demoserver.EntitySearchResponse.total_count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entities', full_name='demoserver.EntitySearchResponse.entities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra_list', full_name='demoserver.EntitySearchResponse.extra_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=396,
  serialized_end=538,
)

_DETAILEDENTITY.fields_by_name['stat'].message_type = _STAT
_LIST.fields_by_name['item'].message_type = _LISTITEM
_ENTITYSEARCHRESPONSE.fields_by_name['entities'].message_type = _DETAILEDENTITY
_ENTITYSEARCHRESPONSE.fields_by_name['extra_list'].message_type = _LIST
DESCRIPTOR.message_types_by_name['EntitySearchRequest'] = _ENTITYSEARCHREQUEST
DESCRIPTOR.message_types_by_name['Stat'] = _STAT
DESCRIPTOR.message_types_by_name['DetailedEntity'] = _DETAILEDENTITY
DESCRIPTOR.message_types_by_name['ListItem'] = _LISTITEM
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['EntitySearchResponse'] = _ENTITYSEARCHRESPONSE

class EntitySearchRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYSEARCHREQUEST

  # @@protoc_insertion_point(class_scope:demoserver.EntitySearchRequest)

class Stat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STAT

  # @@protoc_insertion_point(class_scope:demoserver.Stat)

class DetailedEntity(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DETAILEDENTITY

  # @@protoc_insertion_point(class_scope:demoserver.DetailedEntity)

class ListItem(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTITEM

  # @@protoc_insertion_point(class_scope:demoserver.ListItem)

class List(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LIST

  # @@protoc_insertion_point(class_scope:demoserver.List)

class EntitySearchResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYSEARCHRESPONSE

  # @@protoc_insertion_point(class_scope:demoserver.EntitySearchResponse)


# @@protoc_insertion_point(module_scope)
